version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: collaborative-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: collaborative_code_editor
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: collaborative-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/collaborative_code_editor?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "5000:5000"
    volumes:
      - app_data:/app/files
    restart: always

volumes:
  mysql_data:
  app_data:
